name: flutter_marvel_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  get_storage: ^2.0.3
  http: ^0.13.5
  oxidized: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/spiderman.jpg
    - assets/images/superman.jpeg
    - assets/images/thedarkknightrises.jpg
    - assets/images/aquaman.jpg

  fonts:
    - family: Alliance
      fonts:
        - asset: assets/fonts/AllianceLight.otf
        - asset: assets/fonts/AllianceRegular.otf
        - asset: assets/fonts/AllianceBold.otf

    - family: Neue
      fonts:
        - asset: assets/fonts/NeueMachina-Light.otf
        - asset: assets/fonts/NeueMachina-Medium.otf
        - asset: assets/fonts/NeueMachina-Regular.otf
        - asset: assets/fonts/NeueMachina-Bold.otf
        - asset: assets/fonts/NeueMachina-Black.otf
        - asset: assets/fonts/NeueMachina-Ultrabold.otf
        - asset: assets/fonts/NeueMachina-Ultralight.otf
